### PR TITLE
AlertManager-route-for-interventions-prod

### PR DESCRIPTION
**Pull request by pwyborn**
Why:
[AlertManager route for interventions-prod#2941](https://app.zenhub.com/workspaces/cloud-platform-team-5ccb0b8a81f66118c983c189/issues/ministryofjustice/cloud-platform/2941)

### CODE REVIEW

**Review by razvan-moj — DISMISSED** [review]

**Comment by pwyborn** [comment]
Merge conflicts

**Comment by pwyborn** [comment]
paulwyborn  3:12 PM
Hi David:
Your ticket:
AlertManager-route-for-interventions-prod#1212
Should be complete now - severity “”hmpps-interventions”

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1215
David Lantos:spiral_calendar_pad:  3:17 PM
Thanks Paul!
3:18
I’m wondering — I’d like 2 routes in the end
3:18
1 for prod alerts and non-prod alerts
3:18
should/could the severity reflect that? (edited) 

paulwyborn  3:20 PM
Will it go to a different slack channel?

David Lantos:spiral_calendar_pad:  3:20 PM
yeah in the long run we’d have #interventions-alerts for prod and #interventions-dev-notifications for anything non-prod

paulwyborn  3:22 PM
Do you want me to add the dev one now?
New

David Lantos:
if it’s possible, yes please

**Comment by pwyborn** [comment]
https://github.com/ministryofjustice/cloud-platform-infrastructure/pull/1215

paulwyborn  3:46 PM
Hi David - you should have 2 severities created now for their respective slack channels:
hmpps-interventions-non-prod
hmpps-interventions-prod
 Let me know if any problems?

**Pull request closed without merging**
